@extends('layouts.app')
@section('title', 'Administração · FormAI')
@section('content')
<header class="v2-header"><div><span class="grading-eyebrow">Gestão do FormAI</span><h1>Administração</h1><p>Acompanhe o acesso, as turmas e o funcionamento do sistema.</p></div><div class="v2-header-actions"><a class="btn btn-outline-primary" href="{{ route('admin.academic') }}">Gestão acadêmica</a><a class="btn btn-primary" href="{{ route('admin.users') }}">Gerenciar usuários</a></div></header>
<div class="v2-metrics">@foreach(['Professores ativos', 'Alunos ativos', 'Administradores ativos', 'classrooms', 'activities'] as $key)<article class="card"><span class="metric">{{ $metrics[$key] }}</span><span>{{ ['classrooms' => 'Turmas', 'activities' => 'Atividades'][$key] ?? $key }}</span></article>@endforeach</div>
<section class="card p-4 mb-4"><h2 class="h4">Funcionamento do sistema</h2><p class="text-secondary">Esperas e novas tentativas da IA são diferentes de falhas definitivas.</p>
@php($schedulerHealthy = $operations['scheduler'] && \Illuminate\Support\Carbon::parse($operations['scheduler'])->greaterThan(now()->subMinutes(3)))
<p><strong>Agendador:</strong> {{ $schedulerHealthy ? 'Ativo' : 'Sem sinal recente — verifique o agendador' }}</p>
<dl class="v2-counts">@foreach([[$metrics['queued'], 'Tarefas na fila'], [$operations['waiting'], 'IA na fila / nova tentativa'], [$operations['failed'], 'Falhas definitivas da IA'], [$metrics['failed_jobs'], 'Falhas de processamento']] as [$value, $label])<div><dt>{{ $label }}</dt><dd>{{ $value }}</dd></div>@endforeach</dl>
</section>
<section class="card p-4"><h2 class="h4">Auditoria recente</h2><p class="text-secondary">Os acessos administrativos são auditados.</p><div class="table-responsive mobile-card-table" tabindex="0" role="region" aria-label="Eventos recentes de auditoria"><table class="table"><thead><tr><th scope="col">Quando</th><th scope="col">Ator</th><th scope="col">Evento</th><th scope="col">Rota</th></tr></thead><tbody>@forelse($audits as $audit)<tr><td><span class="mobile-cell-label d-md-none">Quando</span>{{ $audit->created_at->format('d/m H:i:s') }}</td><td><span class="mobile-cell-label d-md-none">Ator</span>{{ $audit->actor?->name ?? 'Sistema' }}</td><td><span class="mobile-cell-label d-md-none">Evento</span>{{ $audit->event }}</td><td><span class="mobile-cell-label d-md-none">Rota</span>{{ $audit->route }}</td></tr>@empty<tr><td colspan="4">Nenhum evento registrado.</td></tr>@endforelse</tbody></table></div></section>
@endsection
