<?php

use Illuminate\Support\Str;

return [
    'default' => env('DB_CONNECTION', 'pgsql'),
    'fallback' => [
        'enabled' => (bool) env('DB_FALLBACK_ENABLED', false),
        'connection' => env('DB_FALLBACK_CONNECTION', 'mysql_local'),
    ],
    'connections' => [
        'sqlite' => ['driver' => 'sqlite', 'url' => env('DB_URL'), 'database' => env('DB_DATABASE', database_path('database.sqlite')), 'prefix' => '', 'foreign_key_constraints' => true],
        'pgsql' => [
            'driver' => 'pgsql',
            'url' => env('DB_URL'),
            'host' => env('DB_HOST', 'aws-0-sa-east-1.pooler.supabase.com'),
            'port' => env('DB_PORT', '5432'),
            'database' => env('DB_DATABASE', 'postgres'),
            'username' => env('DB_USERNAME'),
            'password' => env('DB_PASSWORD'),
            'charset' => 'utf8',
            'prefix' => '',
            'prefix_indexes' => true,
            'search_path' => env('DB_SCHEMA', 'public'),
            'sslmode' => 'require',
            'application_name' => env('DB_APPLICATION_NAME', 'formai'),
            'options' => extension_loaded('pdo_pgsql') ? array_filter([PDO::ATTR_TIMEOUT => 5]) : [],
        ],
        'mysql_local' => [
            'driver' => 'mysql',
            'url' => env('DB_LOCAL_URL'),
            'host' => env('DB_LOCAL_HOST', '127.0.0.1'),
            'port' => env('DB_LOCAL_PORT', '3306'),
            'database' => env('DB_LOCAL_DATABASE', 'formai'),
            'username' => env('DB_LOCAL_USERNAME', 'root'),
            'password' => env('DB_LOCAL_PASSWORD', '12345'),
            'unix_socket' => env('DB_LOCAL_SOCKET', ''),
            'charset' => env('DB_LOCAL_CHARSET', 'utf8mb4'),
            'collation' => env('DB_LOCAL_COLLATION', 'utf8mb4_unicode_ci'),
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([PDO::ATTR_TIMEOUT => 5]) : [],
        ],
        'mysql' => [
            'driver' => 'mysql',
            'url' => env('DB_LOCAL_URL'),
            'host' => env('DB_LOCAL_HOST', env('DB_HOST', '127.0.0.1')),
            'port' => env('DB_LOCAL_PORT', env('DB_PORT', '3306')),
            'database' => env('DB_LOCAL_DATABASE', env('DB_DATABASE', 'formai')),
            'username' => env('DB_LOCAL_USERNAME', env('DB_USERNAME', 'root')),
            'password' => env('DB_LOCAL_PASSWORD', env('DB_PASSWORD', '12345')),
            'unix_socket' => env('DB_LOCAL_SOCKET', env('DB_SOCKET', '')),
            'charset' => env('DB_LOCAL_CHARSET', 'utf8mb4'),
            'collation' => env('DB_LOCAL_COLLATION', 'utf8mb4_unicode_ci'),
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([PDO::ATTR_TIMEOUT => 5]) : [],
        ],
    ],
    'migrations' => ['table' => 'migrations', 'update_date_on_publish' => true],
    'redis' => ['client' => env('REDIS_CLIENT', 'phpredis'), 'options' => ['cluster' => env('REDIS_CLUSTER', 'redis'), 'prefix' => env('REDIS_PREFIX', Str::slug(env('APP_NAME', 'formai')).'-database-')]],
];
